name: Deploy Backend API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 98.70.48.7 >> ~/.ssh/known_hosts

      - name: Copy files to VM
        run: |
          scp -r ./ azureuser@98.70.48.7:/home/azureuser/backend-api

      - name: Deploy and run backend API
        run: |
          ssh azureuser@98.70.48.7 << 'EOF'
            cd /home/azureuser/backend-api

            # Kill any process on port 80
            sudo fuser -k 80/tcp || true

            # Install necessary packages
            sudo apt-get update
            sudo apt-get install -y python3-pip python3-venv authbind

            # Set up authbind for non-root port 80 usage
            sudo touch /etc/authbind/byport/80
            sudo chmod 500 /etc/authbind/byport/80
            sudo chown azureuser /etc/authbind/byport/80

            # Create and activate virtual environment
            python3 -m venv venv
            source venv/bin/activate

            # Upgrade pip and install dependencies
            pip install --upgrade pip
            pip install -r requirements.txt

            # Run the FastAPI app on port 80 using authbind
            nohup authbind --deep venv/bin/uvicorn main:app --host 0.0.0.0 --port 80 > output.log 2>&1 &
          EOF
